### PR TITLE
Round unix timestamps to nearest second

### PR DESCRIPTION
**Pull request by brennan**

### CODE REVIEW

**Comment by hankim813** [comment]
@brennan can you write a unit test for this please? 🙏

**Comment by hankim813** [comment]
lgtm

**Comment by ladanazita** [comment]
@hankim813 @brennan Hey guys! I have another user reporting this issue. Can we get  👀  and 🚢  this?

**Comment by hankim813** [comment]
@ladanazita @brennan deployed!

**Pull request merged**
