### PR TITLE
Update Wootric library version

### PR DESCRIPTION
**Pull request by diegoserranoa**
Update the integration so it uses the latest version of the Wootric library.

### CODE REVIEW

**Comment by diegoserranoa** [comment]
Hi @hankim813 ! Sorry if your not the guy for this but you helped me the last time 😄 
Could you help me here? 🙏

**Comment by diegoserranoa** [comment]
Can somebody help me please? 🙏

**Comment by hankim813** [comment]
@diegoserranoa sorry for the late reply — are there any breaking changes?

**Comment by diegoserranoa** [comment]
Don't worry @hankim813 au contraire, thanks for helping me. No, we're updating so it uses the latest version of the library.

**Comment by hankim813** [comment]
Great, I'm OOO right now but @ccnixon should be able to assist here

**Comment by diegoserranoa** [comment]
Nice, thanks @hankim813 !

**Comment by diegoserranoa** [comment]
Hi @ccnixon can you help me here?

**Comment by ccnixon** [comment]
Hey @diegoserranoa - yes I can try and get this added asap

**Review by ccnixon — APPROVED** [review]

**Comment by ccnixon** [comment]
Hey @diegoserranoa - it looks like when running tests, the sdk is logging the following:

```
'Wootric: Warning: Remove survey immediately before deploying or else customers will be surveyed repeatedly.'
```

Is this expected?

**Comment by diegoserranoa** [comment]
Yeah, how are you testing?

**Comment by ccnixon** [comment]
This is output when running the unit tests with mocha/karma

**Comment by ccnixon** [comment]
I can try and test locally as well in a browser - it might be just a weird sandboxing issue but wanted to check first to see if that was expected

**Comment by diegoserranoa** [comment]
Yeah, it's just a warning for when a `survey_immediately` flag is set true.

**Comment by diegoserranoa** [comment]
Yup, here it is https://github.com/segment-integrations/analytics.js-integration-wootric/blob/master/test/index.test.js#L24

**Comment by ccnixon** [comment]
ahh ok - yeah it looks like that setting is set to true in the tests. I set it to false and that message is gone but I'm seeing: `'Wootric: Modal already loaded.'` as well as: `'Wootric: Warning: Created at invalid, expecting 10-digit Unix timestamp in seconds.'`

**Comment by diegoserranoa** [comment]
`'Wootric: Modal already loaded.'` appears if you're trying to show the survey when it's already being shown. Meaning that somewhere something like `window.wootric("run")` it's trying to be executed and the modal is already loaded.

The second warning means that the `created_at` it's not a Unix timestamp. But the integration is supposed to convert any dates to a 10 digit Unix timestamp.

This also happened with mocha/karma?

**Comment by ccnixon** [comment]
Hey @diegoserranoa - I think it probably makes sense to schedule some work around this update to ensure this is behaving as expected. Unless the old version of the js sdk is breaking anything, we will likely assign this to someone and schedule it into our sprint next week. Just want to make sure we cover all our based before deploying. Does that sound ok?

**Comment by prabhatjha** [comment]
Hey Chris -- The old version of SDK is preventing our mutual customer (I can send you name offline if you want ;-)) from trying our SDK since it does not support new surveys CSAT and CES. Old one only supported NPS. We would appreciate if you could expedite it.

We have more changes coming up but those we can work around your schedule. Hope this helps. Thanks @ccnixon

**Comment by ccnixon** [comment]
Hey @prabhatjha - completely understand. Let's take this convo to email. Can you send a quick note  to chris.nixon@segment.com and brittany.fritsch@segment.com ?

**Comment by hankim813** [comment]
@diegoserranoa @prabhatjha just deployed!

**Comment by prabhatjha** [comment]
Thanks @hankim813 @ccnixon for getting this resolved soon. 🙏

**Comment by diegoserranoa** [comment]
Thanks for all the help @hankim813 @ccnixon !!

**Pull request merged**
